FROM python:2.7-slim

ENV GOOGLE_AUTH_CLIENT_ID ''
ENV GOOGLE_AUTH_CLIENT_SECRET ''
ENV reCAPTCHA_PUBLIC_KEY ''
ENV reCAPTCHA_PRIVATE_KEY ''
ENV WEBEX_CONTACTS ''
ENV LD_LIBRARY_PATH '/usr/local/lib'

COPY ./* /
RUN /docker-setup.sh
